theme: jekyll-theme-minimal
title: I Can Kill Your Browser with a Simple Regex
description: Maciek Rząsa, <a href="https://twitter.com/mjrzasa">@mjrzasa</a>, <a href="https://toptal.com">Toptal</a>
google_analytics: UA-121670409-1
site:
  github:
    owner_url: https://github.com/mrzasa
